##### 1.Sayılardan oluşan bir boyutlu array oluşturun. Arrayi oluştururken sayıların veri tipini integer olarak belirtelim.

Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakalım.

In [1]:
import numpy as np

In [3]:
arr=np.array([6,12,5.4,8,7.9],dtype="int")
arr

array([ 6, 12,  5,  8,  7])

In [4]:
print(arr.ndim)

1


In [5]:
print(arr.size)

5


##### 2. Aşağıda verilen iki boyutlu ve üç boyutlu arrayi oluşturalım. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşalım. 

İki boyutlu array:
[[1,2,6,7],
 [4,3,9,5]]

Üç boyutlu array:
[[[7,5,14],[21,8,11]],
 [[8,6,20],[14,3,9]]]

 

In [7]:
array2=np.array([[1,2,6,7],[4,3,9,5]])
array2

array([[1, 2, 6, 7],
       [4, 3, 9, 5]])

In [9]:
array3=np.array([[[7,5,14],[21,8,11]],
                 [[8,6,20],[14,3,9]]])
array3

array([[[ 7,  5, 14],
        [21,  8, 11]],

       [[ 8,  6, 20],
        [14,  3,  9]]])

In [10]:
print(array2.ndim)
print(array3.ndim)

2
3


In [11]:
print(array2.size)
print(array3.size)

8
12


In [12]:
array2

array([[1, 2, 6, 7],
       [4, 3, 9, 5]])

In [13]:
np.shape(array2)

(2, 4)

In [14]:
array3

array([[[ 7,  5, 14],
        [21,  8, 11]],

       [[ 8,  6, 20],
        [14,  3,  9]]])

In [15]:
np.shape(array3)

(2, 2, 3)

##### 3. İstenilen elamanlara ulaşmak için arrayler üzerinde indexleme işlemi yapalım

In [16]:
#İki boyutlu arraydaki 2 elemanına ulaşalım

In [17]:
array2

array([[1, 2, 6, 7],
       [4, 3, 9, 5]])

In [18]:
array2[0,1]

2

In [19]:
#İki boyutlu arraydaki 7 elemanına ulaşalım

In [20]:
array2[0,3]

7

In [21]:
#Üç boyutlu arraydaki 9 elemanına ulaşalım

In [22]:
array3

array([[[ 7,  5, 14],
        [21,  8, 11]],

       [[ 8,  6, 20],
        [14,  3,  9]]])

In [23]:
array3[1,1,2]

9

In [24]:
#Üç boyutlu arraydaki 5 elemanına ulaşalım

In [25]:
array3[0,0,1]

5

##### 4. Arrayler üzerinde slicing işlemi uygulayalım.

In [26]:
#İki boyutlu arraydaki 2,6 elemanlarına ulaşalım


In [27]:
array2

array([[1, 2, 6, 7],
       [4, 3, 9, 5]])

In [29]:
array2[0,1:3]

array([2, 6])

In [30]:
#İki boyutlu arraydaki 3,9,5 elemanlarına ulaşalım


In [31]:
array2[1,1:]

array([3, 9, 5])

In [32]:
#Üç boyutlu arraydaki 21,8,11 elemanlarına ulaşalım


In [33]:
array3

array([[[ 7,  5, 14],
        [21,  8, 11]],

       [[ 8,  6, 20],
        [14,  3,  9]]])

In [34]:
array3[0,1,:]

array([21,  8, 11])

In [35]:
#Üç boyutlu arraydaki 6,20 elemanlarına ulaşalım


In [36]:
array3[1,0,1:]

array([ 6, 20])

##### 5. 5 satır 3 sütunluk sıfırlardan ve birlerden oluşan iki tane iki boyutlu array oluşturalım. Bu arrayleri satır ve sütun bazında birleştirelim.

In [42]:
a=np.zeros((5,3),dtype="int")
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [43]:
b=np.ones((5,3),dtype="int")
b

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [45]:
np.concatenate([a,b])

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [46]:
np.concatenate([a,b],axis=1)

array([[0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1]])